kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: superset
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
