apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: superset
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      run: superset
  template:
    metadata:
      labels:
        run: superset
    spec:
      containers:
      - image: tylerfowler/superset:0.13.2
        imagePullPolicy: IfNotPresent
        name: superset
        ports:
        - containerPort: 8088
          protocol: TCP
        resources: {}
        stdin: true
        env:
          - name: SUP_META_DB_URI
            value: postgresql://postgres:password@postgres/
        volumeMounts:
          - name: superset
            mountPath: /superset/
        resources:
          limits:
            cpu: .25
            memory: 500Mi    
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: superset
          persistentVolumeClaim:
            claimName: superset
